# Generated by Django 3.2.5 on 2021-12-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(default='deraBassi', max_length=500),
            preserve_default=False,
        ),
    ]
