# Generated by Django 3.2.5 on 2021-12-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_emailotpdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailOtpDB',
            new_name='EmailOtp',
        ),
    ]
