# Generated by Django 3.2.5 on 2021-12-27 05:59

import customauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_myuser_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOtpDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.IntegerField()),
                ('expiryTime', models.DateTimeField(default=customauth.models.getExpiryTime)),
            ],
        ),
    ]
